### PR TITLE
Fix for expected redirects with 201 status code

### PR DESCRIPTION
**Pull request by lrdiv**
When a user POSTs to an endpoint like `/clients`, the server returns a status code of 201, but (incorrectly) expects restler to perform a redirect to the URL specified in the location header. This is an issue with Harvest's API. Here is a workaround for that issue.

### CODE REVIEW

**Comment by lrdiv** [comment]
I've opened an issue here: harvesthq/api#103

Hopefully it will be addressed and this PR won't be necessary.

**Comment by log0ymxm** [comment]
That's good. I suppose we can give them a few days to respond to that api issue. If they don't respond timely or anyone else mentions this as an issue for them we can merge this pull request and make it available. Thanks for the contribution there.

**Comment by impleri** [comment]
It seems like 201 is the correct response. From [W3](http://www.w3.org/Protocols/rfc2616/rfc2616-sec10.html):

> 10.2.2 201 Created
>
> The request has been fulfilled and resulted in a new resource being created. The newly created resource can be referenced by the URI(s) returned in the entity of the response, with the most specific URI for the resource given by a Location header field. The response SHOULD include an entity containing a list of resource characteristics and location(s) from which the user or user agent can choose the one most appropriate. The entity format is specified by the media type given in the Content-Type header field. The origin server MUST create the resource before returning the 201 status code. If the action cannot be carried out immediately, the server SHOULD respond with 202 (Accepted) response instead. 

vs

> 10.3.4 303 See Other
> 
> The response to the request can be found under a different URI and SHOULD be retrieved using a GET method on that resource. This method exists primarily to allow the output of a POST-activated script to redirect the user agent to a selected resource. The new URI is not a substitute reference for the originally requested resource. The 303 response MUST NOT be cached, but the response to the second (redirected) request might be cacheable.
> 
> The different URI SHOULD be given by the Location field in the response. Unless the request method was HEAD, the entity of the response SHOULD contain a short hypertext note with a hyperlink to the new URI(s). 

201 redirects POST for creating a resource, 303 redirects POST for fetching a resource.

**Comment by lrdiv** [comment]
@log0ymxm Seems like this is an issue with restler.js. In their _isRedirect method they only check for 3xx status codes. Feel free to close.

**Pull request closed without merging**
