### PR TITLE
it should be possible to pass params to the query

### PR DESCRIPTION
**Pull request by G3z**
https://github.com/harvesthq/api/blob/master/Sections/Invoices.md

usage example

    harvest.Invoices.list({query: '?from=20150101&to=20151231'}, (err, data)=>{})

### CODE REVIEW

**Comment by G3z** [comment]
maybe we can integrate https://github.com/hapijs/qs to support object params
```javascript
{
   query: {
       from: '20150101',
       to: '20151231'
   }
}
```

**Comment by G3z** [comment]
i dug deeper and it's now possible to make requests like:
```javascript
harvest.Invoices.list({
      from: `${year}0101`,
      to: `${year}1231`,
      status: ['open', 'paid'],
      page: page
    }, cb);
```

the only thing i couldn't make work is `status: ['open', 'paid']`
the array get translated by qs (in restler) as `status[0]=open&status[1]=paid`
while harvest API wants `status[]=open&status[]=paid`

**Comment by log0ymxm** [comment]
I see that you opened https://github.com/harvesthq/api/issues/144, but it was promptly closed. That's too bad they don't want to support multiple values. The change is straightforward, but before merging this, will you want to squash your commits to keep the update clean?

**Comment by G3z** [comment]
actually since api#144 was closed my PR is invalid.
we have to make something like:

```javascript
var qs = require('qs');
Invoices.prototype.list = function (options, cb) {
     var url = '/invoices';
     if(!_isUndefined(options)){
          url += '?' + qs.stringify(options, {arrayFormat: 'brackets'});
     }
     this.client.get(url, {}, cb);
 };

```

this makes qs a requirement.
if this doesn't bother you i'll make another PR

**Pull request closed without merging**
