### PR TITLE
More resilient error handling.

### PR DESCRIPTION
**Pull request by peterbraden**
If you have bad authentication, the callback can be fired without the error, this PR addresses it.

### CODE REVIEW

**Comment by log0ymxm** [comment]
I think travis may have failed because it was using the older architecture. I just tested updating the build with sudo false, and it seems to pass. Will you rebase your PR?

**Comment by peterbraden** [comment]
Still seems to fail for me with the credentials.

**Comment by log0ymxm** [comment]
Looks like travis [won't allow environment variables when it's a pull request](http://docs.travis-ci.com/user/pull-requests/#Security-Restrictions-when-testing-Pull-Requests). 

I fetched and checked the tests locally, and there is an error deleting time entries. Here is the relevant CI entry, https://travis-ci.org/log0ymxm/node-harvest/jobs/83727748

Do your tests pass locally? Do you know what's causing this to fail?

**Comment by peterbraden** [comment]
I was unable to run the unit tests as I don't have a harvest account that I can use for testing, I had to test manually. I think this may fix it though. Sorry for the broken test! It's annoying I can't rely on CI to fix this - I took a look at the travis docs, but I don't see a good solution for this.

**Comment by log0ymxm** [comment]
This looks correct, thanks for the update. Harvest does have a free account tier which can be used for testing, if you wanted to test locally.

**Pull request merged**
