### PR TITLE
Add options to Invoices.list

### PR DESCRIPTION
**Pull request by thomasnordquist**
GET /invoices has filter and pagination options, but they are currently not usable.
The limit if invoices returned by the api is 50, therefore to work with invoices these options are required.
https://github.com/harvesthq/api/blob/master/Sections/Invoices.md

Changes are compatible with my previous PR:
https://github.com/log0ymxm/node-harvest/pull/32

### CODE REVIEW

**Comment by G3z** [comment]
i tired this cleaner approach https://github.com/log0ymxm/node-harvest/pull/27
but it does not work with states `status: ['open', 'paid']` see https://github.com/log0ymxm/node-harvest/pull/27#issuecomment-148335856

that's why i proposed passing a string https://github.com/log0ymxm/node-harvest/pull/30 and leave the responsibility of using `qs` to the user.

in case you are wondering, this is the option needed for `qs` `{arrayFormat: 'brackets'}`

**Comment by log0ymxm** [comment]
Sorry for the lack of response, I've been busy. Are either of you open to helping keep this library maintained?

**Comment by G3z** [comment]
I would love to help mantain this library

**Comment by G3z** [comment]
i think you are not using the `options` variable you created

**Comment by simplyspoke** [comment]
Suggest closing this request and deleting the branch as the current code base has a cleaner solution.

**Comment by log0ymxm** [comment]
Thanks, good call.

**Pull request closed without merging**
